local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/assets" # Location where files will be stored in the repo
public_folder: "src/assets" # The src attribute for uploaded media
logo_url: https://filter-med.netlify.app/_astro/logo-filter-med.DKycxu6U.svg
locale: 'pt/br'
show_preview_links: true
editor:
    preview: true

collections:
  - label: "Home Page"
    name: "home_page"
    folder: "src/content/cms/home_page"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "home_page"}
        - {label: "header title", name: "headertitle", widget: "string"}
        - {label: "header subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image"}
        - label: "home header card"
          name: "home_header_card" 
          widget: "object"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card subtitle", name: "card_subtitle", widget: "string"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
        - label: "home product card"
          name: "home_product_card" 
          widget: "object"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card subtitle", name: "card_subtitle", widget: "string"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
            - {label: "background image", name: "background_image", widget: "image"}
        - label: "home process card"
          name: "home_process_card" 
          widget: "object"
          fields:
            - {label: "card subtitle", name: "card_subtitle", widget: "string"}
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card content", name: "card_content", widget: "text"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
            - {label: "card image", name: "card_image", widget: "image"}
        - {label: "first section title", name: "first_section_title", widget: "string"}
        - {label: "first section subtitle", name: "first_section_subtitle", widget: "string"}
        - label: "home service cards"
          name: "home_service_cards" 
          widget: "list"
          fields:
            - {label: "service name", name: "service_name", widget: "string"}
            - {label: "service image", name: "service_image", widget: "image"}
        - {label: "second section title", name: "second_section_title", widget: "string"}
        - {label: "second section subtitle", name: "second_section_subtitle", widget: "string"}
        - label: "home product division"
          name: "home_product_division" 
          widget: "object"
          fields:
            - {label: "home product division title", name: "home_product_division_title", widget: "string"}
            - label: "home product division types"
              name: "home_product_division_types" 
              widget: "list"
              fields:
              - {label: "home product division types", name: "home_product_division_types", widget: "string"}
        - label: "home product cards"
          name: "home_product_cards" 
          widget: "list"
          fields:
            - {label: "product card name", name: "product_card_name", widget: "string"}
            - {label: "product card content", name: "product_card_content", widget: "text"}
            - {label: "product card image", name: "product_card_image", widget: "image"}

  - label: "Product Page"
    name: "product_page"
    folder: "src/content/cms/product_page"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "product_page"}
        - {label: "header_title", name: "headertitle", widget: "string"}
        - {label: "header_subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image"}
        - label: "product header card"
          name: "product_header_card" 
          widget: "object"
          fields:
            - {label: "card text", name: "card_text", widget: "string"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
        - {label: "section title", name: "section_title", widget: "string"}
        - {label: "first subtitle", name: "first_subtitle", widget: "string"}
        - label: "product section card"
          name: "product_section_card" 
          widget: "list"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card content", name: "card_content", widget: "string"}
            - {label: "card link", name: "card_link", widget: "string"}
        - {label: "second subtitle", name: "second_subtitle", widget: "string"}
        - label: "product service card"
          name: "product_service_card" 
          widget: "object"
          fields:
            - {label: "card content", name: "card_content", widget: "text"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
            - {label: "card image", name: "card_image", widget: "image"}

  - label: "Service Page"
    name: "service_page"
    folder: "src/content/cms/service_page"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "service_page"}
        - {label: "header title", name: "headertitle", widget: "string"}
        - {label: "header subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image"}
        - {label: "main content", name: "main_content", widget: "text"}
        - {label: "main image", name: "main_image", widget: "image"}
        - {label: "section title", name: "section_title", widget: "string"}
        - label: "service card"
          name: "service_card" 
          widget: "list"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card content", name: "card_content", widget: "string"}
        - label: "product service card"
          name: "product_service_card" 
          widget: "object"
          fields:
            - {label: "card content", name: "card_content", widget: "text"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
            - {label: "card image", name: "card_image", widget: "image"}

  - label: "About Page"
    name: "about_page"
    folder: "src/content/cms/about_page"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "about_page"}
        - {label: "header_title", name: "headertitle", widget: "string"}
        - {label: "header_subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image"}
        - label: "first section"
          name: "first_section" 
          widget: "object"
          fields:
            - {label: "first section title", name: "first_section_title", widget: "string"}
            - {label: "first section content one", name: "first_section_content_one", widget: "text"}
            - {label: "first section content two", name: "first_section_content_two", widget: "text"}
            - {label: "first section image", name: "first_section_image", widget: "image"}
        - label: "second section"
          name: "second_section" 
          widget: "object"
          fields:
            - {label: "second section title", name: "second_section_title", widget: "string"}
            - label: "about card"
              name: "about_card" 
              widget: "list"
              fields:
                - {label: "card title", name: "card_title", widget: "string"}
                - {label: "card content", name: "card_content", widget: "string"}
        - label: "third section"
          name: "third_section" 
          widget: "object"
          fields:
            - {label: "third section title", name: "third_section_title", widget: "string"}
            - {label: "third section content one", name: "third_section_content_one", widget: "text"}
            - {label: "third section content two", name: "third_section_content_two", widget: "text"}
            - {label: "third section content tree", name: "third_section_content_tree", widget: "text"}
        - {label: "card button text", name: "card_button_text", widget: "string"}

  - label: "Product Detail Page"
    name: "product_detail_page"
    folder: "src/content/cms/product_detail"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "product_detail_page"}
        - {label: "header_title", name: "headertitle", widget: "string"}
        - {label: "header_subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image"}
        - label: "product detail header card"
          name: "product_detail_header_card" 
          widget: "object"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card content", name: "card_content", widget: "text"}
        - label: "Filter Media Products" 
          name: "filter_media_products" 
          widget: "object" 
          fields:
            - {label: "section title", name: "section_title", widget: "string"}
            - label: "products list" 
              name: "product_list" 
              widget: "list" 
              fields:
              - {label: "product name", name: "product_name", widget: "string"}
              - {label: "product description", name: "product_description", widget: "string"}
              - {label: "product image", name: "product_image", widget: "image"}
        - label: "Complementary Products" 
          name: "complementaty_products" 
          widget: "object" 
          fields:
            - {label: "section title", name: "section_title", widget: "string"}
            - label: "products list" 
              name: "product_list" 
              widget: "list" 
              fields:
              - {label: "product name", name: "product_name", widget: "string"}
              - {label: "product description", name: "product_description", widget: "string"}
              - {label: "product image", name: "product_image", widget: "image"}
        - label: "Lab Filtration Equipment Products" 
          name: "lab_filtration_equipment_products" 
          widget: "object" 
          fields:
            - {label: "section title", name: "section_title", widget: "string"}
            - label: "products list" 
              name: "product_list" 
              widget: "list" 
              fields:
              - {label: "product name", name: "product_name", widget: "string"}
              - {label: "product description", name: "product_description", widget: "string"}
              - {label: "product image", name: "product_image", widget: "image"}
        - label: "Filer Presses And Housing Products" 
          name: "filer_presses_and_housing_products" 
          widget: "object" 
          fields:
            - {label: "section title", name: "section_title", widget: "string"}
            - label: "products list" 
              name: "product_list" 
              widget: "list" 
              fields:
              - {label: "product name", name: "product_name", widget: "string"}
              - {label: "product description", name: "product_description", widget: "string"}
              - {label: "product image", name: "product_image", widget: "image"}
        - label: "product detail card"
          name: "product_detail_card" 
          widget: "object"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card subtitle", name: "card_subtitle", widget: "string"}
            - {label: "card button text", name: "card_button_text", widget: "string"}

