local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/assets" # Location where files will be stored in the repo
public_folder: "src/assets" # The src attribute for uploaded media
logo_url: https://filter-med.netlify.app/_astro/logo-filter-med.DKycxu6U.svg
locale: 'pt/br'
show_preview_links: true
editor:
    preview: true

collections:
  - label: "Home Page"
    name: "home_page"
    folder: "src/cms/home_page"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "home_page"}
        - {label: "header title", name: "headertitle", widget: "string"}
        - {label: "header subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - label: "home header card"
          name: "home_header_card" 
          widget: "object"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card subtitle", name: "card_subtitle", widget: "string"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
        - label: "home product card"
          name: "home_product_card" 
          widget: "object"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card subtitle", name: "card_subtitle", widget: "string"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
            - {label: "background image", name: "background_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - label: "home process card"
          name: "home_process_card" 
          widget: "object"
          fields:
            - {label: "card subtitle", name: "card_subtitle", widget: "string"}
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card content", name: "card_content", widget: "text"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
            - {label: "card image", name: "card_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - {label: "first section title", name: "first_section_title", widget: "string"}
        - {label: "first section subtitle", name: "first_section_subtitle", widget: "string"}
        - label: "home service cards"
          name: "home_service_cards" 
          widget: "list"
          fields:
            - {label: "service name", name: "service_name", widget: "string"}
            - {label: "service image", name: "service_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - {label: "second section title", name: "second_section_title", widget: "string"}
        - {label: "second section subtitle", name: "second_section_subtitle", widget: "string"}
        - label: "home product division"
          name: "home_product_division" 
          widget: "object"
          fields:
            - {label: "home product division title", name: "home_product_division_title", widget: "string"}
            - label: "home product division types"
              name: "home_product_division_types" 
              widget: "object"
              fields:
              - {label: "home product division types", name: "type1", widget: "string"}
              - {label: "home product division types", name: "type2", widget: "string"}
              - {label: "home product division types", name: "type3", widget: "string"}
              - {label: "home product division types", name: "type4", widget: "string"}
        - label: "home product cards"
          name: "home_product_cards" 
          widget: "list"
          fields:
            - {label: "product card name", name: "product_card_name", widget: "string"}
            - {label: "product card content", name: "product_card_content", widget: "text"}
            - {label: "product card image", name: "product_card_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}

  - label: "Product Page"
    name: "product_page"
    folder: "src/cms/product_page"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "product_page"}
        - {label: "header_title", name: "headertitle", widget: "string"}
        - {label: "header_subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - label: "product header card"
          name: "product_header_card" 
          widget: "object"
          fields:
            - {label: "card text", name: "card_text", widget: "string"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
        - {label: "section title", name: "section_title", widget: "string"}
        - {label: "first subtitle", name: "first_subtitle", widget: "string"}
        - label: "product section card"
          name: "product_section_card" 
          widget: "list"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card content", name: "card_content", widget: "text"}
            - {label: "card link", name: "card_link", widget: "string"}
            - {label: "card image", name: "card_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - {label: "second subtitle", name: "second_subtitle", widget: "string"}
        - label: "product service card"
          name: "product_service_card" 
          widget: "object"
          fields:
            - {label: "card content", name: "card_content", widget: "text"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
            - {label: "card image", name: "card_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}

  - label: "Service Page"
    name: "service_page"
    folder: "src/cms/service_page"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "service_page"}
        - {label: "header title", name: "headertitle", widget: "string"}
        - {label: "header subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - {label: "main content", name: "main_content", widget: "text"}
        - {label: "main image", name: "main_image", widget: "image"}
        - {label: "section title", name: "section_title", widget: "string"}
        - label: "service card"
          name: "service_card" 
          widget: "list"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card content", name: "card_content", widget: "string"}
        - label: "product service card"
          name: "product_service_card" 
          widget: "object"
          fields:
            - {label: "card content", name: "card_content", widget: "text"}
            - {label: "card button text", name: "card_button_text", widget: "string"}
            - {label: "card image", name: "card_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}

  - label: "About Page"
    name: "about_page"
    folder: "src/cms/about_page"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "about_page"}
        - {label: "header_title", name: "headertitle", widget: "string"}
        - {label: "header_subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - label: "first section"
          name: "first_section" 
          widget: "object"
          fields:
            - {label: "first section title", name: "first_section_title", widget: "string"}
            - {label: "first section content one", name: "first_section_content_one", widget: "text"}
            - {label: "first section content two", name: "first_section_content_two", widget: "text"}
            - {label: "first section image", name: "first_section_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - label: "second section"
          name: "second_section" 
          widget: "object"
          fields:
            - {label: "second section title", name: "second_section_title", widget: "string"}
            - label: "about card"
              name: "about_card" 
              widget: "list"
              fields:
                - {label: "card title", name: "card_title", widget: "string"}
                - {label: "card content", name: "card_content", widget: "string"}
        - label: "third section"
          name: "third_section" 
          widget: "object"
          fields:
            - {label: "third section title", name: "third_section_title", widget: "string"}
            - {label: "third section content one", name: "third_section_content_one", widget: "text"}
            - {label: "third section content two", name: "third_section_content_two", widget: "text"}
            - {label: "third section content tree", name: "third_section_content_tree", widget: "text"}
        - {label: "card button text", name: "card_button_text", widget: "string"}

  - label: "Product Detail Page"
    name: "product_detail_page"
    folder: "src/cms/product_detail"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "product_detail_page"}
        - {label: "header_title", name: "headertitle", widget: "string"}
        - {label: "header_subtitle", name: "subtitle", widget: "string"}
        - {label: "background image", name: "background_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
        - label: "Filter Media Products" 
          name: "filter_media_products" 
          widget: "object" 
          fields:
            - label: "product detail header card"
              name: "product_detail_header_card" 
              widget: "object"
              fields:
                - {label: "card title", name: "card_title", widget: "string"}
                - {label: "card content", name: "card_content", widget: "text"}
            - {label: "section title", name: "section_title", widget: "string"}
            - label: "products list" 
              name: "product_list" 
              widget: "list"
              fields:
              - {label: "product name", name: "product_name", widget: "string"}
              - {label: "product description", name: "product_description", widget: "text"}
              - {label: "product image", name: "product_image", widget: "image", media_folder: "../../../src/cms//product_detail/filter_media", public_folder: "../../../src/cms//product_detail/filter_media"}
        - label: "Complementary Products" 
          name: "complementaty_products" 
          widget: "object" 
          fields:
            - label: "product detail header card"
              name: "product_detail_header_card" 
              widget: "object"
              fields:
                - {label: "card title", name: "card_title", widget: "string"}
                - {label: "card content", name: "card_content", widget: "text"}
            - {label: "section title", name: "section_title", widget: "string"}
            - label: "products list" 
              name: "product_list" 
              widget: "list" 
              fields:
              - {label: "product name", name: "product_name", widget: "string"}
              - {label: "product description", name: "product_description", widget: "text"}
              - {label: "product image", name: "product_image", widget: "image", media_folder: "../../../src/cms//product_detail/complementary_products", public_folder: "../../../src/cms//product_detail/complementary_products"}
        - label: "Lab Filtration Equipment Products" 
          name: "lab_filtration_equipment_products" 
          widget: "object" 
          fields:
            - label: "product detail header card"
              name: "product_detail_header_card" 
              widget: "object"
              fields:
                - {label: "card title", name: "card_title", widget: "string"}
                - {label: "card content", name: "card_content", widget: "text"}
            - {label: "section title", name: "section_title", widget: "string"}
            - label: "products list" 
              name: "product_list" 
              widget: "list" 
              fields:
              - {label: "product name", name: "product_name", widget: "string"}
              - {label: "product description", name: "product_description", widget: "text"}
              - {label: "product image", name: "product_image", widget: "image", media_folder: "../../../src/cms//product_detail/lab_filtration_equipment", public_folder: "../../../src/cms//product_detail/lab_filtration_equipment"}
        - label: "Filer Presses And Housing Products" 
          name: "filer_presses_and_housing_products" 
          widget: "object" 
          fields:
            - label: "product detail header card"
              name: "product_detail_header_card" 
              widget: "object"
              fields:
                - {label: "card title", name: "card_title", widget: "string"}
                - {label: "card content", name: "card_content", widget: "text"}
            - {label: "section title", name: "section_title", widget: "string"}
            - label: "products list" 
              name: "product_list" 
              widget: "list" 
              fields:
              - {label: "product name", name: "product_name", widget: "string"}
              - {label: "product description", name: "product_description", widget: "text"}
              - {label: "product image", name: "product_image", widget: "image", media_folder: "../../../src/cms//product_detail/filter_presses_and_housings", public_folder: "../../../src/cms//product_detail/filter_presses_and_housings"}
        - label: "product detail card"
          name: "product_detail_card" 
          widget: "object"
          fields:
            - {label: "card title", name: "card_title", widget: "string"}
            - {label: "card subtitle", name: "card_subtitle", widget: "string"}
            - {label: "card button text", name: "card_button_text", widget: "string"}

  - label: "navigation bar"
    name: "navigation_bar"
    folder: "src/cms/navigation_bar"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
      - {label: "title", name: "title", widget: "hidden", default: "navigation_bar"}
      - label: "logo container"
        name: "logo_container"
        widget: "object"
        fields:
          - {label: "text", name: "text", widget: "string"}
          - {label: "logo", name: "logo", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
      - label: "navigation"
        name: "navigation"
        widget: "list"
        fields:
          - {label: "text", name: "text", widget: "string"}

  - label: "footer bar"
    name: "footer_bar"
    folder: "src/cms/footer"
    create: true
    slug: "{{slug}}"
    preview_path: preview/{{slug}}
    fields:
      - {label: "title", name: "title", widget: "hidden", default: "footer_bar"}
      - label: "footer social media"
        name: "footer_social_media"
        widget: "object"
        fields:
          - {label: "text", name: "text", widget: "string"}
          - label: "social media list"
            name: "social_media_list"
            widget: "list"
            fields:
              - {label: "social media image", name: "social_media_image", widget: "image", media_folder: "../../../src/assets", public_folder: "../../../src/assets"}
              - {label: "link", name: "link", widget: "string"}
      - label: "footer navigation"
        name: "footer_navigation"
        widget: "object"
        fields:
          - {label: "name", name: "name", widget: "string"}
          - label: "navigation"
            name: "navigation"
            widget: "list"
            fields:
              - {label: "text", name: "text", widget: "string"}
      - label: "footer address"
        name: "footer_address"
        widget: "object"
        fields:
          - {label: "adress title", name: "adress_title", widget: "string"}
          - {label: "adress text", name: "adress_text", widget: "string"}
          - {label: "phone title", name: "phone_title", widget: "string"}
          - {label: "phone number", name: "phone_number", widget: "string"}
      - label: "copyright"
        name: "copyright"
        widget: "string"