backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/assets" # Location where files will be stored in the repo
public_folder: "src/assets" # The src attribute for uploaded media

collections:
  - label: "Home_Page_Data"
    name: "home_page_data"
    folder: "src/_cms/home_page"
    create: true
    slug: "{{slug}}"
    fields:
        - {label: "title", name: "title", widget: "hidden", default: "home_page_data"}
        - {label: "header_title", name: "headertitle", widget: "string"}
        - {label: "header_subtitle", name: "subtitle", widget: "string"}